# https://i.gyazo.com/38682c2adf56d01422a7266f62c4794f.png
instruments = [
    'Acoustic Grand Piano',
    'Bright Acoustic Piano',
    'Electric Grand Piano',
    'Honky tonk Piano',
    'Electric Piano 1',
    'Electric Piano 2',
    'Harpsichord',
    'Clavi',
    'Celesta',
    'Glockenspiel',
    'Music Box',
    'Vibraphone',
    'Marimba',
    'Xylophone',
    'Tubular Bells',
    'Dulcimer',
    'Drawbar Organ',
    'Percussive Organ',
    'Rock Organ',
    'Church Organ',
    'Reed Organ',
    'Accordion',
    'Harmonica',
    'Tango Accordion',
    'Acoustic Guitar nylon',
    'Acoustic Guitar steel',
    'Electric Guitar jazz',
    'Electric Guitar clean',
    'Electric Guitar muted',
    'Overdriven Guitar',
    'Distortion Guitar',
    'Guitar harmonics',
    'Acoustic Bass',
    'Electric Bass finger',
    'Electric bass pick',
    'Fretless Bass',
    'Slap bass 1',
    'Slap bass 2',
    'Synth bass 1',
    'Synth bass 2',
    'Violin',
    'Viola',
    'Cello',
    'Contrabass',
    'Tremolo Strings',
    'Pizzicato strings',
    'Orchestral Harp',
    'Timpani',
    'String Ensemble 1',
    'String Ensemble 2',
    'Synth strings 1',
    'Synth strings 2',
    'Choir Aahs',
    'Voice oohs',
    'Synth voice',
    'Orchestra Hit',
    'Trumpet',
    'Trombone',
    'Tuba',
    'Muted Trumpet',
    'French Horn',
    'Brass section',
    'Synth brass 1',
    'Synth brass 2',
    'Soprano Sax',
    'Alto Sax',
    'Tenor Sax',
    'Baritone Sax',
    'Oboe',
    'English Horn',
    'Bassoon',
    'Clarinet',
    'Piccolo',
    'Flute',
    'Recorder',
    'Pan Flute',
    'Blown Bottle',
    'Shakuhachi',
    'Whistle',
    'Ocarina',
    'Lead 1 square',
    'Lead 2 sawtooth',
    'Lead 3 calliope',
    'Lead 4 chiff',
    'Lead 6 charang',
    'Lead 6 voice',
    'Lead 7 fifths',
    'Lead 8 bass lead',
    'Pad 1 new age',
    'Pad 2 warm',
    'Pad 3 polysynth',
    'Pad 4 choir',
    'Pad 5 bowed',
    'Pad 6 metallic',
    'Pad 7 halo',
    'Pad 8 sweep',
    'FX 1 rain',
    'FX 2 soundtrack',
    'FX 3 crystal',
    'FX 4 atmosphere',
    'FX 5 brightness',
    'FX 6 goblins',
    'FX 7 echoes',
    'FX 8 sci fi',
    'Sitar',
    'Banjo',
    'Shamisen',
    'Koto',
    'Kalimba',
    'Bag pipe',
    'Fiddle',
    'Shanai',
    'Tinkle bell',
    'Agogo',
    'Steel Drum',
    'Woodblock',
    'Taiko drum',
    'Melodic tom',
    'Synth drum',
    'Reverse cymbal',
    'Guitar fret noise',
    'Breath noise',
    'Seashore',
    'Bird tweet',
    'Telephone ring',
    'Helicopter',
    'Applause',
    'Gunshot',
]